
# Make sure you restart/reload your server when changing one of
# these options. MMOLib/MMOItems/MMOCore are /reload friendly
# but that might not be the case for all the plugins you're using.

# Default: 2.0; crits deal twice as much damage. This value
# stacks up with the current weapon's crit power.
#
# Example:
# - 10 atk damage sword
# - +50% crit power
# - crit coefficient set to 2.0
# result: 25 damage (10 + 10 + 5)
crit-coefficient: 2.0

# Same but for skill damage.
spell-crit-coefficient: 1.5

# Put that option to true if you are updating to MMOLib 1.1+
# Don't use it if you are using MMOLib for the first time.
# Requires a reload when changed.
#
# That option makes sure players all have their base
# attribute value set to the default attribute base value.
fix-player-attributes: true

# Default and max. values of armor stats. These systems
# all have a cooldown which can be reduced using the
# '*** Cooldown Reduction' item stat.
mitigation:

    # Edit mitigation messages here. Leavy blank for no message.
    message:
        action-bar: true
        parry: '&cYou just parried #damage# damage.'
        block: '&cYou just blocked #damage# damage.' # Use #power# to display block power.
        dodge: '&cYou just dodged #damage# damage.'
    
    block:
        power:
            default: 25.0
            max: 75.0
        rating-max: 80.0
        cooldown:
            base: 5.0
            min: 10.0
    dodge:
        knockback:
            enabled: true
            force: 1.0
        rating-max: 80.0
        cooldown:
            base: 5.0
            min: 1.0
    parry:
        knockback:
            enabled: true
            force: 1.0
        rating-max: 80.0
        cooldown:
            base: 8.0
            min: 2.0
